### ISSUE TITLE
CSV Ressource is not being previewed 

### ISSUE THREAD

**Issue by DianaMPG** [ViderumGlobal/ckanext-opnv#2]
The csv ressource https://www.opendata-oepnv.de/dataset/haltestellen-vrr
is not being previewed. 

In comparison: 
The exact same ressource is also on opendata-vrr, but it is previewed correctly
https://vrr.ckan.io/dataset/haltestellen/resource/87b671c8-53ed-4999-a459-871fec5d37e3

**Comment by goranmaxim** [comment]
This has been resolved. Closing
